apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hands-on-lab-platform-engineering-for-ops
  description: Hands-on lab: Platform Engineering for Ops teams
  annotations:
    github.com/project-slug: POps-Rox/hands-on-lab-platform-engineering-for-ops
    backstage.io/techdocs-ref: dir:.
  tags:
    - documentation
    - platform-ops
  links:
    - url: https://github.com/POps-Rox/hands-on-lab-platform-engineering-for-ops
      title: GitHub Repository
      icon: github
spec:
  type: documentation
  owner: platform-ops-team
  lifecycle: production
  system: pops-rox-platform
